version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  api: 
    image: 661813109322.dkr.ecr.eu-central-1.amazonaws.com/jaodi/podcastpwa:api
    ports:
      - "4000:4000"
  static:
    image: 661813109322.dkr.ecr.eu-central-1.amazonaws.com/jaodi/podcastpwa:static
    ports:
      - "80:3000"
